services:
  traefik:
    image: traefik:v3.7.13
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/certs:/var/certs
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config/dynamic.yml:/etc/traefik/dynamic.yml:ro
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    restart: unless-stopped
    labels:
      com.homelab.service: "traefik"
      com.homelab.maintainer: "homelab"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - traefik_network
      - portainer_network
      - unifi_network
      - monitoring_network
      - authentik_network
      - actualbudget_network
      - apple-trans_network
  
  sablier:
    image: sablierapp/sablier:1.18.0
    container_name: sablier
    restart: unless-stopped
    networks:
      - traefik_network
      - apple-trans_network
    command:
      - start
      - "--provider.name=docker" # Tell Sablier to watch Docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Needs access to START/STOP containers
    labels:
      traefik.enable: "true"
      traefik.http.services.sablier.loadbalancer.server.port: "10000"
      traefik.http.routers.sablier.rule: "Host(`sablier.prod.yourdomain.com`)" # Sablier API access (optional)
      


networks:
  traefik_network:
    external: true  
  portainer_network:
    external: true
  unifi_network:
    external: true
  monitoring_network:
    external: true
  authentik_network:
    external: true
  actualbudget_network:
    external: true
  apple-trans_network:
    external: true




