- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: google
    target: _self
    focus: false
    showSearchSuggestions: true

- datetime:
    text_size: xl
    format:
      timeStyle: short
      dateStyle: short
      hour12: true
